### ISSUE TITLE
How did you preprocess the cholecseg8k masks

### ISSUE THREAD

**Issue by JoJoNing25** [josaklil-ai/surg-active-learning#1]
Hi there,

Very interesting work. I want to try running the code on the cholecseg8k dataset. Do you have any suggestions on how to preprocess the watershed masks? When I read them in NumPy arrays, the color code doesn't match with the dataset description. There are 17 unique color codes in the whole dataset, while there are only 13 classes. 

Thanks

**Comment by josaklil-ai** [comment]
Hello,

Thanks for bringing this up! To preprocess the dataset, I read in the watershed masks as grayscale images using PIL, using the following dictionary to reindex grayscale colors to class indices:

C = {0:50, 1:11, 2:21, 3:13, 4:12, 5:31, 6:23, 7:24, 8:25, 9:32, 10:22, 11:33, 12:5}.

**Comment by JoJoNing25** [comment]
Hi Josaklil,

Thanks a lot. That's very helpful :)
